"""empty message

Revision ID: 0672110d31cf
Revises: 068144cd334f
Create Date: 2022-02-08 14:40:52.342154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0672110d31cf'
down_revision = '068144cd334f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shops_city_id_fkey', 'shops', type_='foreignkey')
    op.drop_column('shops', 'city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('city_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('shops_city_id_fkey', 'shops', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
